### ISSUE TITLE
Look at this thing

### ISSUE THREAD

**Issue by Time-dragon** [FunctionalMetatable/FunctionalMetatable#1]
See this thing [here](https://prodigy-math-game.fandom.com/f/p/4400000000000171104).

**Comment by FunctionalMetatable** [comment]
Should be moved to https://github.com/scratchsuite/scratch

**Comment by Time-dragon** [comment]
> Should be moved to https://github.com/scratchsuite/scratch

it's there

**Comment by FunctionalMetatable** [comment]
test
